name: Deploy Ionic On Push to Production
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: ðŸŒŽ Web Update Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ’» Get the latest code
        uses: actions/checkout@v4
      - name: ðŸ“¦ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: ðŸ’» Install Ionic CLI
        run: npm install -g @ionic/cli
      - name: ðŸ“¦ Install Ionic Dependencies
        run: npm install
      - name: â­ï¸ Setting project as "production"
        run: npm run ensure-production
      - name: ðŸ“²ðŸŒŽ Build Ionic Project (Web)
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: npm run bundle-web-update
      - name: ðŸ—³ï¸ Get Bundle name
        id: zip_file
        run: |
          zip_file=$(ls dist/*.zip | head -n 1)
          zip_basename=$(basename "$zip_file")
          echo "zip_file=$zip_file" >> $GITHUB_OUTPUT
          echo "zip_basename=$zip_basename" >> $GITHUB_OUTPUT
      - name: ðŸ“¤ Upload Bundle via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 69.6.214.100
          username: root
          port: 22022
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          source: ${{ steps.zip_file.outputs.zip_file }}
          target: /tmp/bundles/web/
          strip_components: 1
      - name: ðŸš€ Load Bundle on Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 69.6.214.100
          username: root
          port: 22022
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            cd /home/wwimed/maranatha.top/current
            php artisan app:load-bundle --type=Web --filepath="/tmp/bundles/web/${{ steps.zip_file.outputs.zip_basename }}"
            rm -f "/tmp/bundles/web/${{ steps.zip_file.outputs.zip_basename }}"
  native-deploy:
    name: ðŸ“² Native Live Update Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ’» Get the latest code
        uses: actions/checkout@v4
      - name: ðŸ“¦ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: ðŸ’» Install Ionic CLI
        run: npm install -g @ionic/cli
      - name: ðŸ“¦ Install Ionic Dependencies
        run: npm install
      - name: â­ï¸ Setting project as "production"
        run: npm run ensure-production
      - name: ðŸ“²ðŸŒŽ Build Ionic Project (Web and Native)
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: npm run bundle-live-update
      - name: ðŸ—³ï¸ Get Bundle name
        id: zip_file
        run: |
          zip_file=$(ls dist/*.zip | head -n 1)
          zip_basename=$(basename "$zip_file")
          echo "zip_file=$zip_file" >> $GITHUB_OUTPUT
          echo "zip_basename=$zip_basename" >> $GITHUB_OUTPUT
      - name: ðŸ“¤ Upload Bundle via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 69.6.214.100
          username: root
          port: 22022
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          source: ${{ steps.zip_file.outputs.zip_file }}
          target: /tmp/bundles/native/
          strip_components: 1
      - name: ðŸš€ Load Bundle on Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 69.6.214.100
          username: root
          port: 22022
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            cd /home/wwimed/maranatha.top/current
            php artisan app:load-bundle --type=Native --filepath="/tmp/bundles/native/${{ steps.zip_file.outputs.zip_basename }}"
            rm -f "/tmp/bundles/native/${{ steps.zip_file.outputs.zip_basename }}"